title: TC in ML
url: https://tankutcan.github.io
baseurl: ""

permalink: /blog/:year/:month/:day/:title

markdown: kramdown

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
